### ISSUE TITLE
cmake error with linux_configure.sh

### ISSUE THREAD

**Issue by dxli** [rgbdemo/rgbdemo#13]
Hi,

On the master branch, I got an error with linux_configure.sh. Also, the folder nestk is empty from git HEAD

CMake Error at calibration/CMakeLists.txt:11 (NESTK_ADD_EXECUTABLE):
  Unknown CMake command "NESTK_ADD_EXECUTABLE".

Thanks,

dxli

**Comment by dxli** [comment]
due to missing of nestk, closing this issue

**Comment by nburrus** [comment]
You need to download the code with git clone --recursive to download
the submodules. Now you can do a "git submodule update" to download
the nestk submodule.

Cheers,
Nicolas

On Mon, Feb 27, 2012 at 6:11 PM, Dongxu Li
reply@reply.github.com
wrote:
