### ISSUE TITLE
multiple kinect calibration

### ISSUE THREAD

**Issue by hackma** [rgbdemo/rgbdemo#14]
i have updated my application to the latest nestk/rgbdemo version 0.7, but I get now problems with the multiple Kinect calibration. I use two  kinects and need the calibration stuff ;)

In the rgbd-multikinect i grab all frames with the A4 chessboard. I  use two kinects, one in front and one on top. The calibration folder  image count is not sync for each Kinect. (the image count for each Kinect is not the same). I get the same result when I tried it with the –sync parameter. Maybe  I did something wrong or it is still a bug.

In the calibrate-multiple-kinects I get problems. One is that the application mean that the calibration/kinectID folders have the same  image name folder. The rgbd-multikinect generates not the same folder  name for sync images. To fix that I inserted the following:

global::images_list = global:: images_dir.entryList(QStringList("view????*"), QDir::Dirs, QDir::Name);
get_calibrated_kinect_corners(global::images_dir,
                                  global::images_list,
                                  global::calibration,
                                  global::rgbd_processor,
                                  corners);

After that I get the problem that the two Kinect folder have an different image count. Maybe I have an idea how I can fix that, or maybe I did something wrong. But it worked in this way in the rgbdemo 0.6.1 version. I hope you can help me.

Best Regards,
Marco

**Comment by nburrus** [comment]
Should be fixed in latest git versions.
