### ISSUE TITLE
rgbd-scan-markers meshlab problem

### ISSUE THREAD

**Issue by hackma** [rgbdemo/rgbdemo#15]
Hi Nicolas,

i found a problem with the exporter object.model. I scan a object with the marker board an export it to the .model. After that i open the mesh.ply in Meshlab. When i now want to edit something then the tool says under LOG Messages "There are gl errors". I cant edit something in Meshlab. With files generated with scan-topview it works fine, but then i have only a part from the object.

Have you an solution for that?
Thanks

Best Regards,
Marco

**Comment by hackma** [comment]
should i send you the .model folder via email?

**Comment by hackma** [comment]
Fixed ;)

Dont use Meshlab versions < 1.3.0! With ubuntus default version 1.2.x you get this errors.
1.3 works fine

**Comment by nburrus** [comment]
Could you send me the .ply file you cannot modify? I'll check if it works
with my Meshlab install.

Thanks,
Nicolas

**Comment by hackma** [comment]
Hi Nicolas,

after I saw in your video that you have meshlab version 1.3. I have upgraded my old 1.2 meshlab version to 1.3 and now it works ;)

Best Regards,
Marco

-----Ursprüngliche Nachricht-----
Von: Nicolas Burrus [mailto:reply@reply.github.com] 
Gesendet: Freitag, 30. März 2012 20:04
An: Hack, Marco
Betreff: Re: [rgbdemo] rgbd-scan-markers meshlab problem (#15)

Could you send me the .ply file you cannot modify? I'll check if it works with my Meshlab install.

Thanks,
Nicolas

On Thursday, March 29, 2012, Marco wrote:

> Hi Nicolas,
> 
> i found a problem with the exporter object.model. I scan a object with 
> the marker board an export it to the .model. After that i open the 
> mesh.ply in Meshlab. When i now want to edit something then the tool 
> says under LOG Messages "There are gl errors". I cant edit something 
> in Meshlab. With files generated with scan-topview it works fine, but 
> then i have only a part from the object.
> 
> Have you an solution for that?
> Thanks
> 
> Best Regards,
> Marco
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nburrus/rgbdemo/issues/15

---
