### ISSUE TITLE
Vectorial not found as submodule 

### ISSUE THREAD

**Issue by pedropgusmao** [rgbdemo/rgbdemo#22]
Hello, when I try to clone your rgbd repository, I get the following:
Submodule path 'nestk': checked out 'e8af9a187790bd77a9fa77d1f2fba2ed5a3594af'
No submodule mapping found in .gitmodules for path 'deps/vectorial'
Failed to recurse into submodule path 'nestk'

I believe it is missing on the nestk repository but still needed on the rgbd, right? 

Thanks,

**Comment by nburrus** [comment]
Thanks, it should be fixed now. It was added improperly to the repository.
