### ISSUE TITLE
RGBDemo on Windows with libfreenect backend

### ISSUE THREAD

**Issue by orgicus** [rgbdemo/rgbdemo#23]
Hi,

Is there a built version of RGBDemo for Windows using libfreenect ? The default seem to be compiled for OpenNI.
If not, Is there an easier option than setting up an IDE, libraries and recompiling ?

Thank you,
George

**Comment by nburrus** [comment]
Hi,

You can use the --freenect command line option to most of the demos to
enable the freenect backend instead of the default OpenNI.

**Comment by orgicus** [comment]
Hello Nicolas,

Thank you for the quick reply. 
I've tried to run 
`rgbd-viewer.exe --freenect`
and
`rgbd-viewer.exe --freenect true` 
but no joy so far :(
I'm getting:

```
ASSERT failure in: could not create any grabber. Kinect support built ? [grabber]
```

I'm not sure if the error means it doesn't detect a camera or the drivers, or something else.

I'm using RGBDemo-0.7.0-Win32 on Windows XP with the libfreenect drivers.
I can access the camera through wrappers libraries for openframeworks/Processing.

Any hints ?

**Comment by nburrus** [comment]
Argh right, the freenect backend might now be enabled anymore in Windows in
the 0.7 binairies. You would need to compile it from source, sorry.

**Comment by orgicus** [comment]
No worries, thanks! 
I'll try that later on my windows machine.

**Comment by orgicus** [comment]
I've built/installed OpenCV 2.4.2 and then did the same for rgbdemo (git clone with --recursive as advised) and I can do calibration with libfreenect now :) Woo hoo! Thank you again !
