### ISSUE TITLE
Skeleton not drawn/displayed with embedded and latest OpenNI

### ISSUE THREAD

**Issue by hjost** [rgbdemo/rgbdemo#26]
I'm using a 64 bit Ubuntu 12.04 and I encountered a problem with the latest RGB demo from git. The sample program 'rgbd-skeletor' doesn't draw/display a skeleton. The sample prgram 'Sample-NiUserTracker' from OpenNI does draw a skeleton (this should mean that NITE works). The user tracker feature works fine. I have also tried using the embedded OpenNI, but the skeleton isn't  displayed/recognized in either case.

I have so far installed:
- OpenCV 2.4.1
- latest OpenNI (https://github.com/OpenNI/OpenNI.git)
- latest SensorKinect (https://github.com/avin2/SensorKinect.git)
- NITE v1.5.2.21 (x64)

Here is log file:
1346293936094886    INFO          Log    XnLog.cpp    346    New log started on 2012-08-30 04:32:16
1346293936094907    INFO          Log    XnLog.cpp    350    OpenNI version is 1.5.4 (Build 0)-Linux-x86 (Aug 12 2012 00:51:38)
1346293936094915    INFO          Log    XnLog.cpp    319    --- Filter Info --- Minimum Severity: NONE
1346293936094924    INFO          Log    XnLog.cpp    319    --- Filter Info --- Minimum Severity: WARNING
    54317    WARNING       xnOS    LinuxSysVNamedEvents.cpp    130    Open named event: failed to open key file (2) - event might not exist...
  1397052    WARNING       xnOS    LinuxSharedMemory.cpp    136    Could not create file '�oP�' for shared memory (2).

**Comment by nburrus** [comment]
Solved in https://github.com/nburrus/nestk/commit/c39a61a77015a0c56ce95d6b3a98fdf5508d4930
