### ISSUE TITLE
Compiling RGBDemo0.6 with MingW

### ISSUE THREAD

**Issue by modyficater** [rgbdemo/rgbdemo#3]
It seems that some stuff is broken:

started mingw32-make
freenect was compiling and linking, glview.exe was created, then it
starts compiling nestk
gcc (GCC) 4.4.0

[ 35%] Building CXX object nestk/ntk/CMakeFiles/nestk.dir/stats/
distributions.ob
j
D:\kinect\rgbdemo\nestk\ntk\stats\distributions.cpp:1: warning: -fPIC
ignored fo
r target (all code is position independent)
In file included from D:/opencv/OpenCV-2.3.0/include/opencv2/core/
core.hpp:4247,

```
            from D:/opencv/OpenCV-2.3.0/include/opencv/cxcore.h:
```

51,
                from D:/kinect/rgbdemo/nestk/ntk/core.h:25,
                from D:\kinect\rgbdemo\nestk\ntk\stats\/
distributions.h:23,
                from D:\kinect\rgbdemo\nestk\ntk\stats
\distributions.cpp:20:
D:/opencv/OpenCV-2.3.0/include/opencv2/core/operations.hpp: In
function 'void nt
k::mean_empirical_distribution(ntk::EmpiricalDistribution&, const
std::vector<do
uble, std::allocator<double> >&, int, double)':
D:/opencv/OpenCV-2.3.0/include/opencv2/core/operations.hpp:1056:
internal compil
er error: in expand_expr_real_1, at expr.c:7888
Please submit a full bug report,
with preprocessed source if appropriate.
See http://gcc.gnu.org/bugs.html for instructions.
mingw32-make[2]: **\* [nestk/ntk/CMakeFiles/nestk.dir/stats/
distributions.obj] Er
ror 1
mingw32-make[1]: **\* [nestk/ntk/CMakeFiles/nestk.dir/all] Error 2
mingw32-make: **\* [all] Error 2

**Comment by nburrus** [comment]
Closing since this is old now, and mingw is not supported anymore since OpenNI is not compatible with it.
