### ISSUE TITLE
Calibration tools cannot find view directories by default anymore

### ISSUE THREAD

**Issue by laanwj** [rgbdemo/rgbdemo#9]
By default, in RGBDFrameRecorder::getNextFrameDirectory, the camera serial and timestamp is added, resulting in filenames like `grab1/unknown/view0000-0,000000/`. 

However, the calibration tools (such as calibrate_kinect_ir) do not know how to cope with this, and don't find the snapshots... because of this, the calibration sequence as described in http://nicolas.burrus.name/index.php/Research/KinectRgbDemoV6?from=Research.KinectRgbDemoV2 does not work as-is. 

Version: git head (72e007a870)
Edit: wanted to report this to the mailing list, but have to wait for authorization...

**Comment by nburrus** [comment]
You're right, thanks for the report! Will try to fix it before releasing 0.7.0 officially.

**Comment by nburrus** [comment]
Most of these issues should be fixed in
https://github.com/nburrus/rgbdemo/commit/e4af1b7382cf59fa893ba766df6687c43d550ac2
